# site settings
title: Forty
subtitle: by HTML5 UP
email: hannahssdu@gmail.com
description: A software engineer who's passionate about technology<br /> and ready to take on the world.
baseurl: "/forty-jekyll-theme" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author:
city: New York
state: NY
zip_code: 10016
country: United States of America
phone: (650) 526-8587

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url:
github_url: https://github.com/hannahdu
instagram_url: https://instagram.com
linkedin_url: https://www.linkedin.com/in/hannah-du-34008645
pinterest_url:
slack_url:
twitter_url: 

# build settings
markdown: kramdown

sass:
  style: compressed
